name: Complex CI

on: push

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - run: date

  job2:
    name: Second job
    runs-on: windows-latest
    steps:
      - run: date
  job3:
    name: Third job
    runs-on: macos-latest
    steps:
      - run: date
  job4:
    name: Fourth job
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - run: date
      - name: Typescript compiler
        # You may pin to the exact commit or the version.
        # uses: iCrawl/action-tsc@c3f25c126c7805dbbbcbf6f1db0c3be6f5dac069
        uses: iCrawl/action-tsc@v1
